### ISSUE TITLE
SD_Unlocker original author credit

### ISSUE THREAD

**Issue by R3Q13M** [Alia5/SteamDeck_BIOS_UNLOCK#1]
Please credit the original author of the [SD_Unlocker.c](https://github.com/Alia5/SteamDeck_BIOS_UNLOCK/blob/main/SD_Unlocker.c) code, @SmokelessCPUv2

**Comment by syberphunk** [comment]
Yep this should happen since we wouldn't have it without them.

**Comment by TedsGitHubEmporium** [comment]
+1

**Comment by dan2wik** [comment]
This is a line for line copy of the original project from here
https://gist.github.com/SmokelessCPUv2/8c1e6559031e199d9a678c9fe2ebf7d4
Credit for copied code is a must.

**Comment by syberphunk** [comment]
Looks like it's been silently updated.
